/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiDirectRouteImport } from './routes/api/direct'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiReadRouteImport } from './routes/api/read'
import { Route as ApiShotRouteImport } from './routes/api/shot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectRoute = ApiDirectRouteImport.update({
  id: '/api/direct',
  path: '/api/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadRoute = ApiReadRouteImport.update({
  id: '/api/read',
  path: '/api/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShotRoute = ApiShotRouteImport.update({
  id: '/api/shot',
  path: '/api/shot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/direct': typeof ApiDirectRoute
  '/api/health': typeof ApiHealthRoute
  '/api/read': typeof ApiReadRoute
  '/api/shot': typeof ApiShotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/direct': typeof ApiDirectRoute
  '/api/health': typeof ApiHealthRoute
  '/api/read': typeof ApiReadRoute
  '/api/shot': typeof ApiShotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/direct': typeof ApiDirectRoute
  '/api/health': typeof ApiHealthRoute
  '/api/read': typeof ApiReadRoute
  '/api/shot': typeof ApiShotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/studio' | '/api/direct' | '/api/health' | '/api/read' | '/api/shot'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/studio' | '/api/direct' | '/api/health' | '/api/read' | '/api/shot'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/api/direct'
    | '/api/health'
    | '/api/read'
    | '/api/shot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiDirectRoute: typeof ApiDirectRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadRoute: typeof ApiReadRoute
  ApiShotRoute: typeof ApiShotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/direct': {
      id: '/api/direct'
      path: '/api/direct'
      fullPath: '/api/direct'
      preLoaderRoute: typeof ApiDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/read': {
      id: '/api/read'
      path: '/api/read'
      fullPath: '/api/read'
      preLoaderRoute: typeof ApiReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shot': {
      id: '/api/shot'
      path: '/api/shot'
      fullPath: '/api/shot'
      preLoaderRoute: typeof ApiShotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiDirectRoute: ApiDirectRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadRoute: ApiReadRoute,
  ApiShotRoute: ApiShotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
