/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnimaticRouteImport } from './routes/api/animatic'
import { Route as ApiContactsheetRouteImport } from './routes/api/contactsheet'
import { Route as ApiDirectRouteImport } from './routes/api/direct'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiReadRouteImport } from './routes/api/read'
import { Route as ApiStoryboardRouteImport } from './routes/api/storyboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimaticRoute = ApiAnimaticRouteImport.update({
  id: '/api/animatic',
  path: '/api/animatic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsheetRoute = ApiContactsheetRouteImport.update({
  id: '/api/contactsheet',
  path: '/api/contactsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectRoute = ApiDirectRouteImport.update({
  id: '/api/direct',
  path: '/api/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadRoute = ApiReadRouteImport.update({
  id: '/api/read',
  path: '/api/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryboardRoute = ApiStoryboardRouteImport.update({
  id: '/api/storyboard',
  path: '/api/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/animatic': typeof ApiAnimaticRoute
  '/api/contactsheet': typeof ApiContactsheetRoute
  '/api/direct': typeof ApiDirectRoute
  '/api/health': typeof ApiHealthRoute
  '/api/read': typeof ApiReadRoute
  '/api/storyboard': typeof ApiStoryboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/animatic': typeof ApiAnimaticRoute
  '/api/contactsheet': typeof ApiContactsheetRoute
  '/api/direct': typeof ApiDirectRoute
  '/api/health': typeof ApiHealthRoute
  '/api/read': typeof ApiReadRoute
  '/api/storyboard': typeof ApiStoryboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/animatic': typeof ApiAnimaticRoute
  '/api/contactsheet': typeof ApiContactsheetRoute
  '/api/direct': typeof ApiDirectRoute
  '/api/health': typeof ApiHealthRoute
  '/api/read': typeof ApiReadRoute
  '/api/storyboard': typeof ApiStoryboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/animatic'
    | '/api/contactsheet'
    | '/api/direct'
    | '/api/health'
    | '/api/read'
    | '/api/storyboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/animatic'
    | '/api/contactsheet'
    | '/api/direct'
    | '/api/health'
    | '/api/read'
    | '/api/storyboard'
  id:
    | '__root__'
    | '/'
    | '/api/animatic'
    | '/api/contactsheet'
    | '/api/direct'
    | '/api/health'
    | '/api/read'
    | '/api/storyboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnimaticRoute: typeof ApiAnimaticRoute
  ApiContactsheetRoute: typeof ApiContactsheetRoute
  ApiDirectRoute: typeof ApiDirectRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadRoute: typeof ApiReadRoute
  ApiStoryboardRoute: typeof ApiStoryboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/animatic': {
      id: '/api/animatic'
      path: '/api/animatic'
      fullPath: '/api/animatic'
      preLoaderRoute: typeof ApiAnimaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contactsheet': {
      id: '/api/contactsheet'
      path: '/api/contactsheet'
      fullPath: '/api/contactsheet'
      preLoaderRoute: typeof ApiContactsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/direct': {
      id: '/api/direct'
      path: '/api/direct'
      fullPath: '/api/direct'
      preLoaderRoute: typeof ApiDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/read': {
      id: '/api/read'
      path: '/api/read'
      fullPath: '/api/read'
      preLoaderRoute: typeof ApiReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storyboard': {
      id: '/api/storyboard'
      path: '/api/storyboard'
      fullPath: '/api/storyboard'
      preLoaderRoute: typeof ApiStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnimaticRoute: ApiAnimaticRoute,
  ApiContactsheetRoute: ApiContactsheetRoute,
  ApiDirectRoute: ApiDirectRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadRoute: ApiReadRoute,
  ApiStoryboardRoute: ApiStoryboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
